name: Deploy on AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_IP_KEY: ${{ secrets.SSH_PUBLIC_IP_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          ssh -i keyfile ubuntu@"$SSH_PUBLIC_IP_KEY"
          cd watchworthy/
          npm i
          npx tsc
          pm2 kill
          pm2 start src/index.js
